config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :users do
    get '/my_attended_event' => 'users#my_attended_event'
  end
  resources :events do
    resources :event_attendees, only: [:create, :destroy]
  end
  # delete 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id', dependent: :destroy
  has_many :event_attendances, foreign_key: :user_id, class_name: 'EventAttendee', dependent: :destroy
  has_many :attended_events, through: :event_attendances, source: :event, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :my_attended_event]

  def show
    @events = current_user.created_events
  end

  def my_attended_event
    @events = current_user.attended_events
  end
end

app/views/users/_events.html.erb
<% if user_signed_in? %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">Past Events</h2>
            <ul class="list-group">
              <% @events&.each do |event| %>
                <% if event&.event_date < Date.today %>
                  <li class="list-group-item">
                    <h5 class="card-title"><%= link_to event.title, event_path(event) %></h5>
                    <p class="card-text"><%= event.description %></p>
                    <p class="card-text"><small class="text-muted">Event Date: <%= event.event_date %></small></p>
                    <div class="btn-group" role="group" aria-label="Event actions">
                      <% if current_user.id == event.creator_id %>
                        <%= link_to 'Edit Event', edit_event_path(event), class: 'btn btn-sm btn-primary me-2' %>
                        <%= button_to "Delete Event", event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete this event?" }, class: "btn btn-sm btn-danger delete-event-button" %>
                      <% end %>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">Upcoming Events</h2>
            <ul class="list-group">
              <% @events&.each do |event| %>
                <% if event&.event_date >= Date.today %>
                  <li class="list-group-item">
                    <h5 class="card-title"><%= link_to event.title, event_path(event) %></h5>
                    <p class="card-text"><%= event.description %></p>
                    <p class="card-text"><small class="text-muted">Event Date: <%= event.event_date %></small></p>
                    <div class="btn-group" role="group" aria-label="Event actions">
                      <% if current_user.id == event.creator_id %>
                        <%= link_to 'Edit Event', edit_event_path(event), class: 'btn btn-sm btn-primary me-2' %>
                        <%= button_to "Delete Event", event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete this event?" }, class: "btn btn-sm btn-danger delete-event-button" %>
                      <% end %>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/my_attended_event.html.erb
<div class="text-center">
  <h4>Events Attended by Me</h4>
</div>
<%= render 'events' %>

app/views/users/show.html.erb
<div class="text-center">
  <h4>Events Created by Me</h4>
</div>
<%= render 'events' %>