config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :users do
    get '/my_attended_event' => 'users#my_attended_event'
  end
  resources :events do
    resources :event_attendees, only: [:create, :destroy]
  end
  # delete 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :event_attendances, foreign_key: :event_id, class_name: 'EventAttendee', dependent: :destroy
  has_many :attendees, through: :event_attendances, source: :user

  scope :past, -> { where('event_date < ?', Time.now) }
  scope :upcoming, -> { where('event_date >= ?', Time.now) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize_event, only: [:edit, :update, :destroy]

  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event_joined = EventAttendee.where(user_id: current_user, event_id: params[:id])
    @attendees = @event.attendees
  end

  def new
    @event = current_user.created_events.new
  end

  def create
    @event = current_user.created_events.new(event_params)
    if @event.save
      redirect_to user_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = 'Event deleted successfully.'
    else
      flash[:alert] = 'You are not authorized to delete this event.'
    end
    redirect_to user_path(current_user)
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def authorize_event
    unless @event.creator_id == current_user.id
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to events_path
    end
  end

  def event_params
    params.require(:event).permit(:title, :description, :event_date).merge(creator_id: current_user.id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
  <div class="container">
  <%= form_with(model: @event, local: true) do |form| %>
    <%= form.hidden_field :authenticity_token, value: form_authenticity_token %>

    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, id: "event_title", class: "form-control", placeholder: "Enter event title" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, id: "event_description", class: "form-control", placeholder: "Enter event description" %>
    </div>

    <div class="mb-3">
      <%= form.label :event_date, class: "form-label" %>
      <%= form.date_field :event_date, id: "event_event_date", class: "form-control" %>
    </div>

    <%= form.hidden_field :creator_id, value: current_user.id %>

    <div class="mb-3">
      <%= form.submit form.object.new_record? ? 'Create Event' : 'Update Event', class: "btn btn-primary", data: { disable_with: form.object.new_record? ? 'Creating Event...' : 'Updating Event...' } %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="text-center">
  <h3>Edit Event</h3>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="container mt-4">
  <div class="text-center">
    <h3 class="mb-4">Events</h3>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title mb-3">Upcoming Events</h5>
          <% @upcoming_events.each do |event| %>
            <div class="card mb-3">
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                <p class="card-text"><%= event.description %></p>
                <p class="card-text"><small class="text-muted">Event Date: <%= event.event_date %></small></p>
                <a href="<%= event_path(event) %>" class="btn btn-primary">View Event</a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title mb-3">Past Events</h5>
          <% @past_events.each do |event| %>
            <div class="card mb-3">
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                <p class="card-text"><%= event.description %></p>
                <p class="card-text"><small class="text-muted">Event Date: <%= event.event_date %></small></p>
                <a href="<%= event_path(event) %>" class="btn btn-primary">View Event</a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="text-center">
  <h3>New Event</h3>
</div>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="container mt-4">
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">Event</h4>
      <h5 class="card-subtitle mb-2 text-muted"><%= @event.title %></h5>
      <p class="card-text"><%= @event.description %></p>
      <p class="card-text"><small class="text-muted">Event Date: <%= @event.event_date %></small></p>

      <% if @event_joined.empty? %>
        <%= form_with url: event_event_attendees_path(@event), method: :post, local: true do %>
          <%= submit_tag 'Join Event', class: 'btn btn-primary' %>
        <% end %>
      <% else %>
        <%= form_with url: event_event_attendee_path(@event, current_user), method: :delete, local: true do %>
          <%= submit_tag 'Leave Event', class: 'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Attendees</h5>
      <% if @attendees.any? %>
        <ul class="list-group list-group-flush">
          <% @attendees.each do |attendee| %>
            <li class="list-group-item"><%= attendee.email %></li>
          <% end %>
        </ul>
      <% else %>
        <p class="card-text">No attendees yet.</p>
      <% end %>
    </div>
  </div>
</div>