config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :users do
    get '/my_attended_event' => 'users#my_attended_event'
  end
  resources :events do
    resources :event_attendees, only: [:create, :destroy]
  end
  # delete 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>">Private Events</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Events Created", user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Events", user_my_attended_event_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Create New Event", new_event_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>

  <body>
    <div>
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>